name: Documentation
on:
  push:
    tags:
    - 'v*'
jobs:
  docs:
    runs-on: ubuntu-latest
    name: Generate
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
      
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build autodoc
      run: |
        go build -v -o autodoc $(go list ./cmd/autodoc)

    - name: Generate mkdocs from templates
      run: mkdir -p docs/{datasources,resources} && ./autodoc
    
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python3 -m pip install mkdocs
        
    - run: mkdocs build
  
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./html
